# 서버용 Dockerfile

# 베이스 이미지 설정
FROM ubuntu:latest

# 의존성 설치
RUN apt-get update && \
    apt-get install -y gcc libc6-dev make

# 작업 디렉토리 설정
WORKDIR /server

# 서버 소스 코드 복사
COPY server.c .

# 서버 코드 컴파일
RUN gcc -o server server.c -lpthread

# 서버가 리스닝하는 포트 노출
EXPOSE 12345

# 서버 실행 명령
CMD ["./server", "12345"]

