# 클라이언트용 Dockerfile

# 베이스 이미지 설정
FROM ubuntu:latest

# 의존성 설치
RUN apt-get update && \
    apt-get install -y gcc libc6-dev make

# 작업 디렉토리 설정
WORKDIR /client

# 클라이언트 소스 코드 복사
COPY client.c .

# 클라이언트 코드 컴파일
RUN gcc -o client client.c

# 클라이언트 실행 명령
# 환경 변수로 서버 IP 주소와 포트를 받음
CMD ["./client", "172.18.0.2", "12345", "one"]

